### ISSUE TITLE
Error on Gulp process

### ISSUE THREAD

**Issue by rygos** [Hifone/Hifone#116]
Hi,
if i run Gulp i get the following Error Message:

```
marcels-mbp:HifoneGulb ryg$ gulp
/Users/ryg/PhpstormProjects/HifoneGulb/node_modules/laravel-elixir/GulpPaths.js:100
        if (path.indexOf('./') == 0) {
                ^

TypeError: Cannot read property 'indexOf' of undefined
  at prefixOne (/Users/ryg/PhpstormProjects/HifoneGulb/node_modules/laravel-elixir/GulpPaths.js:100:17)
  at [object Object].GulpPaths.prefix (/Users/ryg/PhpstormProjects/HifoneGulb/node_modules/laravel-elixir/GulpPaths.js:120:12)
  at [object Object].GulpPaths.src (/Users/ryg/PhpstormProjects/HifoneGulb/node_modules/laravel-elixir/GulpPaths.js:20:16)
  at prepGulpPaths (/Users/ryg/PhpstormProjects/HifoneGulb/node_modules/laravel-elixir/tasks/coffee.js:55:10)
  at Function.<anonymous> (/Users/ryg/PhpstormProjects/HifoneGulb/node_modules/laravel-elixir/tasks/coffee.js:19:17)
  at Function.<anonymous> (/Users/ryg/PhpstormProjects/HifoneGulb/node_modules/laravel-elixir/index.js:40:18)
  at /Users/ryg/PhpstormProjects/HifoneGulb/gulpfile.js:26:10
  at Elixir (/Users/ryg/PhpstormProjects/HifoneGulb/node_modules/laravel-elixir/index.js:16:5)
  at Object.<anonymous> (/Users/ryg/PhpstormProjects/HifoneGulb/gulpfile.js:15:1)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
  at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:193:16)
  at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
  at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:185:9)
  at /usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:159:9
  at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:108:14
  at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:36:12
  at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:47:7
  at nextTickCallbackWith0Args (node.js:420:9)
  at process._tickCallback (node.js:349:13)
  at Function.Module.runMain (module.js:443:11)
  at startup (node.js:139:18)
  at node.js:968:3
```

i tried this with Windows and OSX. maybe i have the wrong versions of nodejs, npm or bower?

i made a clean checkout, composer install, npm install, bower install.
then gulp. With no success.

i get this issue since the following commit:
https://github.com/Hifone/Hifone/commit/2e133adedd5438254ad653359910ad38b09c2743

Thx

**Comment by lianguan** [comment]
nodejs: 4.4.7
npm: 1.3.10
bower: 1.7.9

**Comment by rygos** [comment]
My Configuration:
nodejs: 4.4.7
npm: 2.15.8
bower: 1.7.9

I have a newer Version of Nodejs. But this Version does not make any Problems before. I check this. Thanks =)

**Comment by lianguan** [comment]
@rygos 

Package.json in a clean environment may not be able to work. You can confirm this job, and then send a PR. Thanks very much.
