### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by zqhong** [Hifone/Hifone#154]
# My Environment

Ubuntu 14.04.4 LTS 
nginx/1.9.11
PHP 7.0.3-13+deb.sury.org~trusty+1

.env file setting
APP_ENV=production
APP_DEBUG=false
APP_URL=http://hifone.app
APP_KEY=SOME_RANDOM_STRING
APP_TIMEZONE=Asia/Shanghai
# The error I meet

I try to install Hifone, but have two error:
## One of error is:

```
[2016-07-30 22:53:19] production.ERROR: ErrorException: file_put_contents(/home/vagrant/Code/Hifone/storage/app/stringblade/d41d8cd98f00b204e9800998ecf8427e): failed to open stream: No such file or directory in /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php:7364
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/home/vagrant/C...', 7364, Array)
#1 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(7364): file_put_contents('/home/vagrant/C...', '', 0)
#2 /home/vagrant/Code/Hifone/vendor/hifone/stringblade/src/Hifone/StringBlade/StringBladeCompiler.php(48): Illuminate\Filesystem\Filesystem->put('/home/vagrant/C...', '')
#3 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(15326): Hifone\StringBlade\StringBladeCompiler->compile(NULL)
#4 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(15161): Illuminate\View\Engines\CompilerEngine->get(NULL, Array)
#5 /home/vagrant/Code/Hifone/vendor/hifone/stringblade/src/Hifone/StringBlade/StringBlade.php(87): Illuminate\View\View->getContents()
#6 /home/vagrant/Code/Hifone/vendor/hifone/stringblade/src/Hifone/StringBlade/StringBlade.php(63): Hifone\StringBlade\StringBlade->renderContents()
#7 /home/vagrant/Code/Hifone/app/Composers/AppComposer.php(42): Hifone\StringBlade\StringBlade->render()
#8 [internal function]: Hifone\Composers\AppComposer->compose(Object(Illuminate\View\View))
#9 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(14680): call_user_func_array(Array, Array)
#10 [internal function]: Illuminate\View\Factory->Illuminate\View\{closure}(Object(Illuminate\View\View))
#11 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(10136): call_user_func_array(Object(Closure), Array)
#12 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(14693): Illuminate\Events\Dispatcher->fire('composing: inst...', Array)
#13 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(15148): Illuminate\View\Factory->callComposer(Object(Illuminate\View\View))
#14 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(15133): Illuminate\View\View->renderContents()
#15 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(16375): Illuminate\View\View->render()
#16 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(15876): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#17 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(8374): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#18 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(9467): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#19 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /home/vagrant/Code/Hifone/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(9950): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(9468): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(9455): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Hifone\Http\Controllers\InstallController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#25 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(8525): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Hifone\\Http\\Con...', 'index')
#26 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(8512): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#27 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(8226): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /home/vagrant/Code/Hifone/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 /home/vagrant/Code/Hifone/app/Http/Middleware/RedirectIfInstallCompleted.php(35): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Hifone\Http\Middleware\RedirectIfInstallCompleted->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(9965): call_user_func_array(Array, Array)
#33 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /home/vagrant/Code/Hifone/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 /home/vagrant/Code/Hifone/app/Http/Middleware/Pjax.php(32): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Hifone\Http\Middleware\Pjax->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(9965): call_user_func_array(Array, Array)
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /home/vagrant/Code/Hifone/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(3225): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(9965): call_user_func_array(Array, Array)
#43 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /home/vagrant/Code/Hifone/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(13463): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(9965): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /home/vagrant/Code/Hifone/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(11956): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(9965): call_user_func_array(Array, Array)
#53 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /home/vagrant/Code/Hifone/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#55 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(13202): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(9965): call_user_func_array(Array, Array)
#58 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /home/vagrant/Code/Hifone/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#60 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(13139): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#61 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(9965): call_user_func_array(Array, Array)
#63 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /home/vagrant/Code/Hifone/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#65 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(9950): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#67 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(8227): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#68 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(8218): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#69 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(8208): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#70 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(2419): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#71 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#72 /home/vagrant/Code/Hifone/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#73 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(3286): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#74 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#75 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(9965): call_user_func_array(Array, Array)
#76 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 /home/vagrant/Code/Hifone/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#78 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#79 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(9950): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#80 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(2366): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#81 /home/vagrant/Code/Hifone/bootstrap/cache/compiled.php(2350): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#82 /home/vagrant/Code/Hifone/public/index.php(61): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#83 {main} {"identification":{"id":"3ba04bd1-9d4a-4f73-8fc7-e3e6c6663162"}} 

```

In my case, I make a directory named `/home/vagrant/Code/Hifone/storage/app/stringblade` to fix it.
## Another error is:

```
$ git clone https://github.com/Hifone/Hifone
$ cd Hifone
$ cp .env.example .env
# Write database settings
# But I forget to set APP_KEY. The config file will cache at Hifone/bootstrap/cache/config.php.(change .env file is not effect)
$ vi .env    
$ composer install --no-dev -o
$ php artisan hifone:install

$ chmod -R 777 storage
$ chmod -R 777 bootstrap/cache
$ chmod -R 777 public/uploads
```

**Comment by rygos** [comment]
You have run:
composer install?

You can try
php artisan vendor:publish

**Comment by zqhong** [comment]
Well, I have run the command `composer install`. But  users will have puzzled while cache the config file.

And then, I perform the command `php artisan vendor:publish`, the folder `storage/app/stringblade` is created. But it also have some issue that document have not word about it.

I am a newbie for Laravel and Hifone. Thank you for reply me.

**Comment by rygos** [comment]
Okay, i will add the vendor:publish command to the documentation =)
